### PR TITLE
Update to 2.24.4

### PR DESCRIPTION
**Pull request by knackaron**
Signed-off-by: Aron Parsons <aparsons@knackworks.com>

### CODE REVIEW

**Review by jeffsheltren — APPROVED** [review]

**Comment by jeffsheltren** [comment]
Thanks @knackaron! I'll get this pushed to IUS testing right away.

**Comment by jeffsheltren** [comment]
git224-2.24.4-1.el7.ius has been pushed to IUS Testing.

**Comment by jobenvil** [comment]
> git224-2.24.4-1.el7.ius has been pushed to IUS Testing.

@jeffsheltren Do you know when this will be included in IUS Stable?

**Comment by carlwgeorge** [comment]
It's already there.

https://repo.ius.io/7/x86_64/packages/g/git224-2.24.4-1.el7.ius.x86_64.rpm

**Comment by jobenvil** [comment]
@carlwgeorge Thanks for pointing this out. Is there a way to stay tuned (maillist, etc) about new IUS updates regarding this repo?

**Comment by carlwgeorge** [comment]
Major announcements are posted as issues on https://github.com/iusrepo/announce.  Routine package updates are not announced anywhere.  We tag each package NVR in this git repository, so perhaps there is a way in GitHub to get notifications for that.

**Comment by jobenvil** [comment]
Thanks again for your clarification. Somehow I overlooked yesterday the new tag of 11th March. My bad 🤦 . I marked your link (https://repo.ius.io/7/x86_64/packages/g/?sort=time&order=desc), but it's clear enough. Keep the good work 👍

**Comment by carlwgeorge** [comment]
Don't feel bad, you didn't overlook it.  The tag didn't exist yesterday, I just created it.  We forgot to tag it when the package was built.  Sorry about that.  What you are seeing as the date of the tag is the date of the commit it references.

**Pull request merged**
